name = "BlochSim"
uuid = "5c0f8cbe-99a4-11e9-108b-216da9629524"
authors = ["Steven Whitaker <stwhit@umich.edu>"]
version = "0.7.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ForwardDiff = "0.10"
julia = "1.2"
