name = "BlochSim"
uuid = "5c0f8cbe-99a4-11e9-108b-216da9629524"
authors = ["Steven Whitaker <stwhit@umich.edu>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.0"
