[deps]
BlochSim = "5c0f8cbe-99a4-11e9-108b-216da9629524"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MIRTjim = "170b2178-6dee-4cb0-8729-b3e8b57834cc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
